name: CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-network:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test Network Connectivity
        run: |
          echo "Testing network connectivity to EC2 instance"
          ping -c 4 ec2-3-138-134-13.us-east-2.compute.amazonaws.com
          curl -I http://ec2-3-138-134-13.us-east-2.compute.amazonaws.com
          nc -zv ec2-3-138-134-13.us-east-2.compute.amazonaws.com 22
