name: CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  connect-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEYPAIR }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Connect to EC2 and create folder
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-138-134-13.us-east-2.compute.amazonaws.com "mkdir -p /home/ec2-user/success"
