name: CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant execute permission for Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build and Test Spring Boot Backend
        run: ./mvnw clean install
        id: build-backend

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      
      - name: Install dependencies and build React Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build Docker Images
        run: docker-compose -f ./task-management/docker-compose.yml build

      - name: Set up SSH key
        run: |
          echo "$EC2_KEYPAIR" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-18-227-140-222.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-18-227-140-222.us-east-2.compute.amazonaws.com 'cd /task_management && docker-compose up -d'
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

